import OpenAI from 'openai';
export const runtime='nodejs';
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const reviewSchema={type:'object',additionalProperties:false,properties:{overall:{type:'string'},strengths:{type:'array',items:{type:'string'}},improvements:{type:'array',items:{type:'object',additionalProperties:false,properties:{area:{type:'string'},feedback:{type:'string'},nextStep:{type:'string'}},required:['area','feedback','nextStep']}},beforeSubmit:{type:'array',items:{type:'string'}},rubricChecks:{type:'array',items:{type:'object',additionalProperties:false,properties:{criterion:{type:'string'},status:{type:'string'},feedback:{type:'string'}},required:['criterion','status','feedback']}}},required:['overall','strengths','improvements','beforeSubmit','rubricChecks']};
const assignmentSchema={type:'object',additionalProperties:false,properties:{id:{type:'string'},title:{type:'string'},subject:{type:'string'},dueDate:{type:'string'},summary:{type:'string'},tasks:{type:'array',items:{type:'string'}},rubricSummary:{type:'array',items:{type:'object',additionalProperties:false,properties:{criterion:{type:'string'},summary:{type:'string'}},required:['criterion','summary']}},fullRubric:{type:'string'},teacherInstructions:{type:'string'},finalReview:{anyOf:[reviewSchema,{type:'null'}]}},required:['id','title','subject','dueDate','summary','tasks','rubricSummary','fullRubric','teacherInstructions','finalReview']};
const schema={type:'object',additionalProperties:false,properties:{assignments:{type:'array',items:assignmentSchema}},required:['assignments']};
const allowed=new Set(['English','한국어','Español','中文']);
export async function POST(req){try{
 const {assignments,language}=await req.json();
 if(!Array.isArray(assignments)||!assignments.length||!allowed.has(language))return Response.json({error:'Invalid assignments or language.'},{status:400});
 const sources=assignments.map(x=>{const b=x.sourceAssignment||x;return {id:String(x.id),title:b.title||'',subject:b.subject||'',dueDate:b.dueDate||'',summary:b.summary||'',tasks:b.tasks||[],rubricSummary:b.rubricSummary||[],fullRubric:b.fullRubric||'',teacherInstructions:x.originalTeacherInstructions||b.teacherInstructions||'',finalReview:x.finalReview||null}});
 const style=language==='한국어'?'Natural Korean for a student. Checklist items use concise ~하기 forms.':language==='Español'?'Natural student-friendly Spanish. Checklist items use concise infinitive action phrases.':language==='中文'?'Natural concise Simplified Chinese for a student. Checklist items use short action phrases.':'Natural concise English for a student.';
 const prompt=`You are the single localization engine for TaskLens. Localize ALL assignments below into ${language} in ONE atomic response. ${style}\n\nNON-NEGOTIABLE:\n1. Every student-facing field must be in ${language}: title, subject, dueDate, summary, every task, rubric criteria and summaries, fullRubric, teacherInstructions, and every finalReview field.\n2. Do not return bilingual text and do not preserve ordinary source-language phrases. Translate ordinary academic/anatomy terms.\n3. Keep only true proper nouns, course/rubric codes such as EBCS1, product names such as Canvas, filenames, and file extensions such as PDF/JPG/PNG unchanged when appropriate.\n4. Preserve exact facts, numbers, dates, times, deliverables, constraints and rubric meaning. Never add or remove requirements.\n5. Localize date/time wording naturally without changing its value.\n6. Keep each id exactly unchanged. Return every input assignment exactly once.\n7. teacherInstructions must be readable and organized, but must not append the source-language original.\n8. If a field is empty, keep it empty.\n\nBefore returning, verify that every assignment uses ONE language consistently.\n\nSOURCE ASSIGNMENTS:\n${JSON.stringify(sources)}`;
 const r=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:prompt,text:{format:{type:'json_schema',name:'localized_assignments',strict:true,schema}}});
 const out=JSON.parse(r.output_text);
 if(out.assignments?.length!==sources.length)throw new Error('Localization returned an incomplete assignment set.');
 return Response.json(out);
}catch(e){console.error(e);return Response.json({error:e?.message||'Localization failed.'},{status:500})}}
